- doc/fidget.md
- lua/fidget.lua
Allow positioning relative to the editor, closes #13
Also:
- Customizable `zindex`
- Customizable `winblend`
- Check if window/buffer valid before closing them (comes into play with something like forced wipeouts from the user)
- Use `next(...)` for checking if items exist in a map-like table
---
With editor-relative positioning, it isn't super easy to know things like the width of the `&signcolumn`/`&foldcolumn` for the left-most window, so that is not handled. Otherwise, things like `&cmdheight`, tabline, statusline, etc. should all be handled.
> Editor-relative positioning

- lua/fidget.lua
This fixes the bug reported in #10 where LSP tasks were being shared
with different fidgets. This bug is because of the shared object
`base_fidget.tasks`, which instead should be deep-copied.
Fix #10.
> Fix a bug where tasks were shared across different fidgets

- doc/fidget.md
- doc/fidget.txt
- lua/fidget.lua
Supercedes #34 (I wasn't able to push to @dsully's branch).
The primary change here is I changed around how each source can be configured. Right now, the only option is to ignore a source, but in the future I want to add the option to silence reporting tasks from each source, which someone suggested to keep the plugin less noisy.
> Allow configuration to ignore sources

- doc/fidget.md
- lua/fidget.lua
Workaround for #28, suggested by @wookayin .
Note that this does not actually disable notifications coming from a source, it just kills the spinner if notifications have ceased. If there are new notifications, the spinner will be started again.
TODO:
> Add FidgetClose command

- lua/fidget.lua
> fix: Use nvim_win_hide to prevent command-line window errors

- lua/fidget.lua
Fix for #29. We defer invocation of fidget:fmt() (in which fidget windows are created) until it's safe to call nvim APIs.
> Fix for #29: Defer drawing fidgets to avoid not-allowed-here errors.

- lua/fidget.lua
clangd sends progress floats with absurd precision drawing a lot of attention. Format these without a decimal.
Before
After
Tested also with rust-analyzer and it did not show any negative side-effects.
> Format float percentage without decimals

- lua/fidget.lua
Neovim just merged support for global status line which allows to have a single status line for all windows.
Fidget is rendering on top of it instead of above it as it would for non global status line.
> Handle new neovim global status line support

- lua/fidget.lua
When reloading your `init.lua`, for those brave enough to try and reloading all modules, lspconfig will stop the client and restart it. Some plugins handle this well, others less so. In the case of fidget it seems to always expect the client
https://github.com/j-hui/fidget.nvim/blob/cbe0db4f2adfddfd830310e5846f8735d4e068fa/lua/fidget.lua#L324
This PR fixes this, so it checks first if the client exists before continuing with the function which requires access to this. This doesn't change or break any functionality from my testing, it just prevents fidget exploding when my config is reloaded
> bugfix: check client exists before access

- doc/fidget.md
- doc/fidget.txt
- lua/fidget.lua
Hi, thanks for your work on this plugin. I certainly appreciate visual feedback while LSPs are still loading :+1: 
This PR allows returning a falsy value in the task `fmt` function, in which case no task line will be displayed (as opposed to an empty line). This allows ignoring specific tasks if the user isn't interested in them.
It also allows setting the `fmt` to false to never show tasks altogether. This is useful for users who are only interested in the spinner but not the task descriptions at all.
> handle falsy task values

- lua/fidget.lua
I was looking towards using both fidget, and lualine-lsp-progress, and being able to enable/disable fidget as necessary.
I haven't looked to see if there is enable/disable commands yet, but here is work towards getting both working in the same session...
With this patch you have to load lsp_utils first, and then fidget calls it. since it is that order `is_installed` should continue working.
where lualine-lsp-progress doesn't have anything like `is_installed`.  I don't think this is a particularly ecosystem wide scalable practice.  But I'm not sure it is any worse than clobbering each others callbacks?
If setup in the correct order no changes to lualine-lsp-progress should be needed, should just work.
> Call an existing callback if there is one

- lua/fidget.lua
winbar is a new feature in neovim 0.8.0 (see :help winbar).
When winbar is enabled, the effective window height should be
decreased by 1 so that the fidget window do not span the boundary.
Fixes #81
> Add winbar support

- lua/fidget.lua
Hi @j-hui!
I have added an filetype to the fidget buffer. This helps identifying the buffer / window in user configs.
This might be helpful for others as well.
This was just a quickfix for myself. Let me know if theres anything that should be added (like documentation, etc.).
Best regards!
> add filetype option to fidget buffer

- lua/fidget.lua
Add an option to set the window border.
Motivation: The default `blend` is 100 meaning totally transparent and it will be blended with the code under it. To avoid this we may change `blend` to a smaller value. But, the window is still hard to recognize especially when it is above a large piece of code. Adding a border will make fidget window easy to tell and prettier.
Thank you.
> feat: support window border

- lua/fidget.lua
Hey!
I grew frustrated of some Neovim crashes that kept happening as I was closing Neovim with modified buffers. After a bunch of debugging I noticed that there were 2 related problems:
1. fidget.nvim kept processing notifications after `VimLeavePre` autocmd fired (which produces annoying but harmless logs in the terminal after existing Neovim, as mentioned in #86 and #110)
2. Calling `nvim_buf_delete` on a fidget buffer when it was the current buffer (which crashed Neovim)
Here is a Neovim backtrace from this situation
[backtrace.txt](https://github.com/j-hui/fidget.nvim/files/9945897/bt.txt)
This was particularly annoying because modified buffers were not saved when this happened. Neovim crashed before it got to writing the buffers.
I tried to come up with better heuristics when calling …
> Ignore progress notifications on `VimLeavePre` and fix crash on exit

- doc/fidget.md
- doc/fidget.txt
This is just a minor thing I noticed, when I set the option `debug.logging` to **true** in the setup function, the actual file where the log was being written to was `~/.local/share/nvim/fidget.nvim.log`, and not `~/.local/share/fidget.nvim.log`, as stated in the docs.
I did a quick peek at the code, and apparently this path is being decided by the `stdpath('data')` function, which on both neovim 0.7.0 and 0.8.2 returns `~/.local/share/nvim`.
I tried on these versions because they are the minimum required version mentioned in the readme (0.7.0) and the one that I use (0.8.2).
I don't know if it was okay to just create a PR or if I should have an issue, sorry if it was a bit intrusive!
And of course, many thanks for your work, such a nice plugin! :blush:
> Fix log file path in documentation

- lua/fidget.lua
> Prevent overlapping windows when border is set

- doc/fidget.md
- doc/fidget.txt
- lua/fidget.lua
Some LSP server are very chatty, and when they send too many messages in a short burst the area taken by fidget.nvim becomes so large that it covers up some of the editing window area.
The new option (defaulted to `2`) limits the number of messages shown at any given time.
**Current behavior**
**New behavior**
Fixes #122
> feat(options): added `max_messages` option

- lua/fidget.lua
quick hack, there's probably a better solution then to just ignore the error.
edit: fixes #136
> Fix error when command-line window is open

- doc/fidget.md
- lua/fidget/notification.lua
- lua/fidget/notification/view.lua
general idea: instead of having a `lines` and `highlights` arrays that we append to, we create an array of "rendered items" which then get converted into the `lines` and `highlights` arrays with correct ordering.
A `render_item` just contains the lines and `render_item` relative highlights.
Not sure about: https://github.com/0xAdk/fidget.nvim/blob/12f4be2e4f2e887b4aeec97b0d392fdd2c4794d6/lua/fidget/notification/view.lua#L144-L152
I went from `string.gmatch` to `vim.gsplit` since it's cleaner and in testing found gmatch implicitly converts from numbers to strings, so I added it explicitly.
Set stack_upwards to `true` by default since that was how legacy worked.
closes #152
> feat!: add stack upwards option

- doc/fidget.md
- doc/fidget.txt
- lua/fidget/notification/window.lua
This adds the `window.dynamic_positioning` option, which will essentially set the value of `align_bottom` depending on which half of the screen the cursor is currently in.
https://github.com/j-hui/fidget.nvim/assets/47333659/811d409d-eb79-434c-9f65-daf42dc97cb8
> feat!: option to position window away from cursor

- .github/workflows/luarocks.yml
- .github/workflows/release-please.yml
Hey :wave: 
This PR is part of a push to get neovim plugins on [LuaRocks](https://luarocks.org/labels/neovim).
* See [this blog post](https://mrcjkb.github.io/posts/2023-01-10-luarocks-tag-release.html), which follows up on [a series of posts](https://teto.github.io/posts/2021-09-17-neovim-plugin-luarocks.html) by @teto.
* See also: [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim), a new luarocks-based plugin manager.
* Add a release-please workflow that creates release PRs with SemVer versioning based on conventional commits
(I noticed you've been using these recently).
* Add a workflow that publishes tags to LuaRocks when a tag or release is pushed.
The workflows are based on [this guide](https://github.com/vhyrro/sample-luarocks-plugin) by @vhyrro.
* On each merge to `main`, …
> ci: automatic releases + publish to luarocks

- doc/fidget-api.txt
- lua/fidget/progress.lua
- lua/fidget/progress/handle.lua
- scripts/build-api-docs.sh
This is something I've been wanting for a while, since the only way to do it (until now) was to create a mock LSP server/client using `vim.lsp.start()`. This PR adds a function `progress.create()` which returns a reactive progress handle, allowing for progress messages to be created and easily updated by users in their configs or in other plugins.
The handle is identical to the `ProgressMessage` type, except it has methods for reporting / completing the progress and is reactive to changes so the user doesn't need to call `notify` repeatedly.
Could also be simplified if the reactivity isn't needed, so all updates would be done with `ProgressHandle:report()` .
Still needs docs and stuff, but figured I'd open up a PR with what I have to see if there's interest.
> feat: public progress API for non-lsp use cases

- lua/fidget/integration/nvim-tree.lua
To handle the error below:
I noticed in the original code that the `winid` property was invoked (with `()`) even when it was `nil`. 
The refined code incorporates a validation step to ensure that the function is called exclusively when a valid value is present.
> fix: checking for winid value before to evoke it

- README.md
- lua/fidget/integration.lua
- lua/fidget/integration/nvim-tree.lua
- lua/fidget/integration/xcodebuild-nvim.lua
- lua/fidget/notification/window.lua
Resolves #207
Also fixes off-by-one error in nvim-tree x_offset adjustment
> feat(integration): xcodebuild.nvim integration (#207)

- lua/fidget/integration/xcodebuild-nvim.lua
I discovered one problem with xcodebuild.nvim integration - when there is a window below (like Trouble or nvim-dap, or anything else), then Fidget is still offset even though there is no collision with xcodebuild.nvim plugin.
I fixed that by checking if there is any other window below Test Explorer.
After fix:
https://github.com/j-hui/fidget.nvim/assets/3128467/4c5e8672-247e-48d9-a72f-bbe36bc06501
> feat(integration): improved avoidance of Test Explorer window from xcodebuild.nvim plugin

- lua/fidget/notification/window.lua
Hey there!
This is fixing the following plugin crash which occurs for me after opening then closing window splits. Function `nvim_tabpage_list_wins` looks to require at least one argument
```
Error executing vim.schedule lua callback: .../fidget.nvim/lua/fidget/poll.lua:119: .../fidg
et.nvim/lua/fidget/notification/window.lua:182: .../fidget.nvim/lua/fidget/notification/window.lua:193: Expected 1 a
rgument
stack traceback:
[C]: in function 'error'
.../fidget.nvim/lua/fidget/poll.lua:119: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
> fix: missing argument for nvim_tabpage_list_wins

- lua/fidget/integration/xcodebuild-nvim.lua
Hi, a small improvement, now the Test Explorer can be already shown when Neovim starts, so we need to handle this case.
> fix(integration): improved avoidance of Test Explorer (xcodebuild.nvim)

- lua/fidget/progress.lua
- lua/fidget/progress/lsp.lua
This change updates the lsp progress implementation to keep track of known client ids (by monitoring the `LspProgress` event). Later when getting a list of clients we can then use this list instead of calling `vim.lsp.get_clients` which only returns active clients.
This allows showing progress notifications for clients before they have completed initializing.
Closes #177
> feat: show progress for clients before they initialize

- lua/fidget/notification.lua
Just stumbled upon this while reading the docs. It's not much but it's honest work.
I assembled the commit name from other commits. Let me know if something should be changed.
> doc: fix typo in notification documentation

- lua/fidget/integration/nvim-tree.lua
winid might be nil if view.float.enable = true inside of nvim-tree
closes #259
> Integration: nvim-tree: Fix crash if winid is nil

- doc/fidget-api.txt
I was playing around with the api's and noticed a missing comma in the documentation example code. Thanks for all the hard work on this plugin.
> chore(doc): fix minor syntax error in progress.handle.create example code

- lua/fidget/notification/window.lua
Fix a rendering crash that occurs when starting nvim with `-c "set nomodifiable"` and remove redundant buffer clearing since `nvim_buf_delete` removes the buffer regardeless of its contents.
> fix(window): safely update buffer lines

- lua/fidget/notification/window.lua
vim's buffers seem to always have at least one line (see the Related issue for a discussion about potentially changing this), so we can't create an empty buffer and then add lines one by one to it. That results in an extra line at the top. Visible with the following config:
```lua
require'fidget'.setup {
notification = {
window = {
border = "rounded",
winblend = 0,
},
},
}
```
The fix is to `vim.api.nvim_buf_set_lines` all the empty lines we'll need at once.
Related: https://github.com/neovim/neovim/issues/34272
Fixes: 2635400d77bf ("feat: render notifications with extmarks")
> fix: avoid empty line at the top
